channels:
- conda-forge
dependencies:
- python=3.12.1
- pip
- pip:
  - mlflow==2.20.2
  - cloudpickle==3.1.1
  - matplotlib==3.10.0
  - numpy==2.2.2
  - pandas==2.2.3
  - psutil==6.1.1
  - pyarrow==18.1.0
  - scikit-learn==1.6.1
  - scipy==1.15.1
name: mlflow-env
